apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-web-app
  name: flask-web-app
spec:
  selector:
    app: flask-web-app
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    protocol: TCP

