apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
      - name: flask-web-app
        image: slong97/flask-web-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: RECOMMENDATIONS_HOST
          value: recom-service
        - name: CATALOGUE_HOST
          value: cat-service

