apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
     containers:
     - name: rabbitmq
       image: slong97/rabbitmq:latest
       ports:
       - containerPort: 5672
       env:
       - name: RABBITMQ_DEFAULT_USER
         value: "admin"
       - name: RABBITMQ_DEFAULT_PASS
         value: "admin"


